### PR TITLE
Migrate from 'error-chain' to 'failure'.

### PR DESCRIPTION
**Pull request by andy128k**
**Do not merge**

I've introduced enums for different errors. There are still few string-based errors.
I'm not sure if such granularity of errors is needed. Docs are also missing.

### CODE REVIEW

**Comment by tafia** [comment]
This is a breaking change that is very expected, thank you for all your work!

Do you see any drawback in using failure over error-chain so far? 
How was the transition (I want to use it on some other libs because of the no_std).

**Comment by andy128k** [comment]
@tafia 
`error-chain`'s macro is a custom syntax and gives cryptic errors if you make a typo.
In opposite, syntax of `failure` is just a rust with annotation. (Frankly speaking, `failure` also could be cryptic if you make error in `#[fail()]` annotation).

`error-chain` gives a single error type for your module with finite list of possible errors (ErrorKind enum). But `failure::Error` is an umbrella which can hold ANY error. So, maybe `failure::Error` is not a good choice for a library and custom error type should be defined (with derived Fail).

As soon as this error type is a part of library's API, it must be well defined. It could be enum (to mimic `error-chain`) or just a string-based struct (for simplicity). This is the question to be answered before any migrations.

**Comment by andy128k** [comment]
@tafia I've updated code. Now it defines two error enums, `errors::Error` and `escape::EscapeError`. All string errors are replaced by corresponding cases of Error enum.

**Comment by tafia** [comment]
Thanks.
It looks ready to be merged and I have tried using Failure in some other projects and it is nice!
Do you want me to merge it now?

**Comment by andy128k** [comment]
Please merge.

**Comment by tafia** [comment]
Thanks!

**Pull request merged**
