### PR TITLE
Remove duplicated tests

### PR DESCRIPTION
**Pull request by Mingun**
Some old tests are unnecessary anymore, because new, more structured tests, already testing the same things:

From `serde-migrated.rs`:

Test                    |Reason
------------------------|----------------------------------------------
test_doctype            |not testing anything useful - doctype not parsed because it is deprecated technology
test_parse_i64          |covered by `serde-de::trivial` tests
test_parse_u64          |covered by `serde-de::trivial` tests
test_parse_bool         |covered by `serde-de::trivial` tests
test_parse_unit         |covered by `serde-de::unit` tests
test_parse_f64          |covered by `serde-de::trivial` tests
test_parse_struct       |covered by `serde-de::struct_` tests
test_amoskvin           |covered by `serde-de::struct_` and `serde-de::seq` tests
test_nicolai86          |covered by `serde-de::struct_` and `serde-de::seq` tests. Sequence fields should me marked as `#[serde(default)]` or be wrapped in Option to be able to deserialize from empty list
test_hugo_duncan2       |covered by `serde-de::struct_` and `serde-de::seq` tests
test_hugo_duncan        |covered by `serde-de::struct_` and `serde-de::unit` tests
test_parse_xml_value    |covered by `serde-de::explicit_value` test
test_parse_complexstruct|test 1 just incorrect; tests 2 and 3 covered by `serde-de::unit`, `serde-de::tuple`, and `serde-de::seq` tests
test_parse_attributes   |covered by `serde-de::explicit_value`, `serde-de::struct_` and `serde-de::nested_struct` tests
test_parse_hierarchies  |covered by `serde-de::struct_`, `serde-de::nested_struct` and `serde-de::seq` tests. Sequence fields should me marked as `#[serde(default)]` or be wrapped in Option to be able to deserialize from empty list
unknown_field           |covered by `serde-de::struct_` and `serde-de::seq` tests
futile                  |covered by `serde-de::trivial` tests
futile2                 |covered by `serde-de::trivial` tests

From `serde_roundtrip.rs`:

Test                    |Reason
------------------------|----------------------------------------------
basic_struct            |covered by `serde-de::struct_` tests
no_contiguous_fields    |covered by `serde-de::seq` tests
escapes_in_cdata        |covered by `serde-de::trivial::struct::cdata` tests

### CODE REVIEW

**Comment by Mingun** [comment]
I am going to merge this in next hour or two, so if there are any objections, it's time to share them.

**Comment by dralley** [comment]
I was about halfway through, but it looks fine so far so :+1: to merging

**Comment by dralley** [comment]
Sorry for being slow.  A few months ago I had more free time than currently but I'm working through them and I'll let you know if I'm just not able to do one.

**Comment by Mingun** [comment]
Ok. It's fine. Anyway, in next week or two I will work on namespaces support and partially on the encoding problems (they are slightly coupled) so you will have time to review currently open PRs

**Pull request merged**
