### PR TITLE
Add test for cancelling read_event_into_async() future

### PR DESCRIPTION
**Pull request by giorgi-o**
Addresses https://github.com/tafia/quick-xml/issues/624#issuecomment-1807077043

### CODE REVIEW

**Comment by Mingun** [comment]
Thanks for PR! It is useful. I (or someone else who is interested) use it when I'll deal with the problem, but for now let it hang open.

**Comment by Mingun** [comment]
Probably this bug is OS-dependent. I tried to increase for loops to `0..3000` and didn't get errors on Windows 11

**Comment by Mingun** [comment]
In case if GitHub delete logs -- error is
```
failures:

---- test_cancel_future stdout ----
thread 'test_cancel_future' panicked at tests/async-tokio.rs:79:22:
called `Result::unwrap()` on an `Err` value: IllFormed(MismatchedEnd { expected: "<tag", found: "tag" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by giorgi-o** [comment]
Note that I am also running Windows 11, and the error occurs consistently on my machine.

**Comment by Mingun** [comment]
Well, then I can say, that you probably should try to debug and fix it yourself. I'll plan to make a PR with completely new parser soon, which maybe will free of this error, so you can wait until that.

Because you already did some debugging, maybe you can rewrite the test to be more straightforward, without loops, just with manual calls in sequence. I think that currently the test unstable because it rely on system timer.

**Comment by giorgi-o** [comment]
I refactored it to be more deterministic, removing the arbitrary loop and replacing the 1ms timeout with 100ms.

As for fixing the issue myself, I'll see if I can make time to get familiar with the codebase, although I unfortunately doubt I can in the next few weeks. Hopefully the new parser addresses the problem.

**Comment by giorgi-o** [comment]
And now it crashes on my machine but not on CI... I'll have to take a closer look

**Pull request closed without merging**
