### PR TITLE
Fix underflow on shrink

### PR DESCRIPTION
**Pull request by lilianmoraru**
Would like to also create a UT for this but I am very busy for the next 3 weeks.
I might reduce the bug later and make another PR with the UT that reproduces the bug.

### CODE REVIEW

**Comment by lilianmoraru** [comment]
Without displaying to much info, here is a reduced stack backtrace:
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow'
stack backtrace:
...
  12:     0x7ff6e38cfe7c - core::panicking::panic
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/panicking.rs:54
  13:     0x7ff6e388107d - quick_xml::writer::Indentation::shrink
                               at .../github.com-1ecc6299db9ec823/quick-xml-0.18.1/src/writer.rs:178
  14:     0x7ff6e37f641a - quick_xml::writer::Writer<std::io::cursor::Cursor<alloc::vec::Vec<u8>>>::write_event<std::io::cursor::Cursor<alloc::vec::Vec<u8>>,quick_xml::events::Event>
                               at .../github.com-1ecc6299db9ec823/quick-xml-0.18.1/src/writer.rs:106
```

**Comment by lilianmoraru** [comment]
Introduces regression, not the correct fix.

**Comment by lilianmoraru** [comment]
Sorry, nvm, the fix is ok, the parsing is incorrect in `master` also, when using `ident_size: 1`.

**Comment by lilianmoraru** [comment]
`ident_size: 1` doesn't play well with `reader.trim_text(true);` but that's a separate issue.

**Comment by tafia** [comment]
Thanks!

**Pull request merged**
