### PR TITLE
Nested Struct and Enum Serialization

### PR DESCRIPTION
**Pull request by dbcfd**
This PR fixes issues with nested struct and enum serialization, where the struct name will be serialized multiple times, or enum name will serialized. Unit variant enums are supported as well.

### CODE REVIEW

**Comment by dbcfd** [comment]
One test is still failing, and it seems to be an issue in the deserializer.

```shell
Serialized: <Nested><A><Nm>Banana</Nm><Src>Store</Src></A><B><Cnt>2</Cnt><Nodes><Boolean>false</Boolean><EOF/></Nodes></B></Nested>

called `Result::unwrap()` on an `Err` value: Xml(EndEventMismatch { expected: "B", found: "Nested" })
thread 'nested_struct' panicked at 'called `Result::unwrap()` on an `Err` value: Xml(EndEventMismatch { expected: "B", found: "Nested" })'```

**Comment by dbcfd** [comment]
Found a couple more issues with added test cases, will be adjusting this branch more.

**Comment by dave-andersen** [comment]
This PR fixes the bug I'm seeing with nested struct names getting duplicated, but it leaves in several debugging println! statements that render it unusable until fixed. :-)

```Attempting to activate pending: Pending=Some("annotation")   Fields=[]
(annotation) Start: Fields=[]
(folder) Pending: Fields=[Some("annotation")]```

**Comment by Ten0** [comment]
Does this fix `flatten` and untagged enums?

**Comment by dbcfd** [comment]
See the test cases added as part of this PR. Without this PR, those test cases will fail. 

I no longer am working on the project with the dataset that led to this PR, so would recommend at least bringing in the test cases from this PR, and improving the implementation to make those tests pass. This PR is one possible implementation, but there's probably a better implementation.

**Comment by Ten0** [comment]
Should we maybe still try to merge it? I'm sure I wouldn't be alone to benefit from the serde support working better :)

**Comment by Mingun** [comment]
Since merging #490 both problems are fixed:
- struct name no more serialized multiple times
- enum name is not serialized. Type names are no more serialized at all

**Pull request closed without merging**
