### PR TITLE
Fix minor bug for parsing comment tag

### PR DESCRIPTION
**Pull request by yawara**
The following code terminates with panic `thread 'main' panicked at 'slice index starts at 6 but ends at 4', libcore/slice/mod.rs:1971:5`.

```rust
extern crate quick_xml;

use quick_xml::events::Event;
use quick_xml::Reader;

fn main() {
    let xml = "<a></a><!-->-->";
    let mut reader = Reader::from_str(&xml);
    reader.trim_text(true);
    let mut buf = Vec::new();
    loop {
        match reader.read_event(&mut buf) {
            Ok(Event::Comment(ref e)) => {
                println!("Comment: \"{}\"", reader.decode(e));
            }
            Ok(Event::Eof) => break,
            Err(e) => println!("Error: {:?}", e),
            _ => (),
        }
    }
}
```

### CODE REVIEW

**Comment by tafia** [comment]
Thanks for the fix!
Could you add a test to make sure it won't happen again?
Could you also run the latest version of rustfmt-preview on stable?

**Comment by yawara** [comment]
@tafia I added the test.

If I run rustfmt on stable, the codes which I don't write will be changed because stable rust 1.29 was released yesterday.

**Comment by tafia** [comment]
Thanks!

**Comment by tafia** [comment]
Pushed v0.12.4

**Pull request merged**
