### PR TITLE
Add zero-copy deserialization

### PR DESCRIPTION
**Pull request by SergioBenitez**
This effectively rebases #208 on the current tip and fixes up some, but certainly not all, of the issues I spotted along the way. The `html5` test is not passing (I'm not sure why it expects bad utf-8?) and neither are the tests that were previously commented out which I assume means they weren't passing then, either.

I'd love to see this merged. I won't have futher time myself to continue working on this, but I thought I'd nudge it in the right direction. I've given @andreivasiliu commit access to the fork and the owners of this repository have access as well. Feel free to work in the fork or take this work and fork it itself and PR - whatever. Also don't feel the need to maintain my authorship of this PR in any way. Please do quite literally whatever you wish with this.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Is there interest in this?

**Comment by dralley** [comment]
I expect there is, he's just been unresponsive for a few weeks (not a criticism, just how it goes!)

**Comment by tafia** [comment]
Sorry for the long delay in answering. I have reviewed it and I am not sure I understand it all so I didn't want to merge too quickly ... then life happened. I'll to it this week

**Comment by tafia** [comment]
Alright after far too many months, I have finally reviewed this PR.

Thanks SO MUCH for this work, there is not much to say. I have rebased it on current master and made tiny cosmetic modifications.

**Comment by tafia** [comment]
I'll probably make a new version very soon in case you're still interested.

**Comment by Mingun** [comment]
@tafia, you probably need to merge Prs more carefully, because this was badly merged with master and broke compilation. Also, it is quite big and not very well structured -- I don't know what else it can break.

**Comment by dralley** [comment]
To be fair, it looks like the Github CI is broken, *silently*.  As in the jobs [failed](https://github.com/tafia/quick-xml/actions/runs/1117558602) (to run) without any warning on the PR.

That's a huge UX issue on the part of Github, and I think the problems (the compilation failure at the very least) would have been pretty obvious if not for that.

@tafia Thank you for spending some time to get things reviewed and merged

**Pull request merged**
