### PR TITLE
Escape Text::Event on write

### PR DESCRIPTION
**Pull request by huntiep**
Per rust-syndication/rss#32. What did you mean by "special characters represented by their ascii code"?

### CODE REVIEW

**Comment by tafia** [comment]
Sorry for the very late answer.

Most of the time escaping is a no-op. I would then expect `escape` to return a `Cow`. Could you try replicating the logic we have in unescape fn for instance to postpone operations as much as possible?

**Comment by tafia** [comment]
Thanks for the change!
Could you please add a test to be sure we won't regress in the future?

**Comment by huntiep** [comment]
Sorry this took so long. I was on vacation and it slipped my mind when I got back.

**Comment by tafia** [comment]
Thanks!!

**Comment by tafia** [comment]
Fyi, I just published version 0.9.0 including your PR.

**Comment by huntiep** [comment]
Awesome!

**Comment by andy128k** [comment]
The same issue is present in Attribute. I suppose From<(&str, &str)> for Attribute should call escape too.

**Pull request merged**
