### PR TITLE
Add `allow_unmatched_ends` reader config option

### PR DESCRIPTION
**Pull request by torokati44**
Fixes https://github.com/tafia/quick-xml/issues/770.

### CODE REVIEW

**Review by Mingun — APPROVED** [review]
Thanks! Could you add a changelog entry, like I did that in #771:
- In **New Features** section add `- [#772]: <short description>`
- In the end of **Unreleased** section add `[#772]: https://github.com/tafia/quick-xml/pull/772` (that is place for all links for a release)
- Keep two blank lines between link from the previous point and section of the last released version, so each releases separated by two blank lines

**Comment by torokati44** [comment]
Yep, there you go, I hope I did it right.

**Comment by torokati44** [comment]
Can we expect a `v0.35.0` on `crates.io` sometime soon?

**Comment by Mingun** [comment]
Yes, I think I release new version in the end of week. I have two ready-to-merge PRs with bug fixes which I want to include in this release because they likely will be accepted in this time.

**Comment by torokati44** [comment]
Great, thanks!

**Comment by Mingun** [comment]
I just released [0.35.0](https://github.com/tafia/quick-xml/releases/tag/v0.35.0).

**Pull request merged**
